package com.foxconn.remote.control.model;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table tb_machine.
 */
public class Machine  implements Serializable{

    private Long id;
    private String machineName;
    private String machineType;
    private String machineBrand;
    private String serialNo;
    private byte[] img;
    private Boolean status;
    private Integer column;
    private long roomId;
    /** 
     * edit by KrisLight not auto-generated
     */
    private Boolean removeFlag = false;

    public Boolean isRemoveFlag() {
		return removeFlag;
	}

	public void setRemoveFlag(Boolean removeFlag) {
		this.removeFlag = removeFlag;
	}

    public Machine() {
    }

    public Machine(Long id) {
        this.id = id;
    }

    public Machine(Long id, String machineName, String machineType, String machineBrand, String serialNo, byte[] img, Boolean status, Integer column, long roomId) {
        this.id = id;
        this.machineName = machineName;
        this.machineType = machineType;
        this.machineBrand = machineBrand;
        this.serialNo = serialNo;
        this.img = img;
        this.status = status;
        this.column = column;
        this.roomId = roomId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMachineName() {
        return machineName;
    }

    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }

    public String getMachineType() {
        return machineType;
    }

    public void setMachineType(String machineType) {
        this.machineType = machineType;
    }

    public String getMachineBrand() {
        return machineBrand;
    }

    public void setMachineBrand(String machineBrand) {
        this.machineBrand = machineBrand;
    }

    public String getSerialNo() {
        return serialNo;
    }

    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    public byte[] getImg() {
        return img;
    }

    public void setImg(byte[] img) {
        this.img = img;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Integer getColumn() {
        return column;
    }

    public void setColumn(Integer column) {
        this.column = column;
    }

    public long getRoomId() {
        return roomId;
    }

    public void setRoomId(long roomId) {
        this.roomId = roomId;
    }

}
