package com.foxconn.remote.control.model;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table tb_base_machine_type.
 */
public class ManchineType implements Serializable{

    private Long id;
    private String typeDes;

    public ManchineType() {
    }
    

    public ManchineType(Long id) {
        this.id = id;
    }
    
    public ManchineType(String typeDes) {
        this.typeDes = typeDes;
    }

    public ManchineType(Long id, String typeDes) {
        this.id = id;
        this.typeDes = typeDes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTypeDes() {
        return typeDes;
    }

    public void setTypeDes(String typeDes) {
        this.typeDes = typeDes;
    }

}
