package com.foxconn.remote.control.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.foxconn.remote.control.model.Room;
import com.foxconn.remote.control.model.Machine;
import com.foxconn.remote.control.model.ManchineType;

import com.foxconn.remote.control.dao.RoomDao;
import com.foxconn.remote.control.dao.MachineDao;
import com.foxconn.remote.control.dao.ManchineTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig roomDaoConfig;
    private final DaoConfig machineDaoConfig;
    private final DaoConfig manchineTypeDaoConfig;

    private final RoomDao roomDao;
    private final MachineDao machineDao;
    private final ManchineTypeDao manchineTypeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        roomDaoConfig = daoConfigMap.get(RoomDao.class).clone();
        roomDaoConfig.initIdentityScope(type);

        machineDaoConfig = daoConfigMap.get(MachineDao.class).clone();
        machineDaoConfig.initIdentityScope(type);

        manchineTypeDaoConfig = daoConfigMap.get(ManchineTypeDao.class).clone();
        manchineTypeDaoConfig.initIdentityScope(type);

        roomDao = new RoomDao(roomDaoConfig, this);
        machineDao = new MachineDao(machineDaoConfig, this);
        manchineTypeDao = new ManchineTypeDao(manchineTypeDaoConfig, this);

        registerDao(Room.class, roomDao);
        registerDao(Machine.class, machineDao);
        registerDao(ManchineType.class, manchineTypeDao);
    }
    
    public void clear() {
        roomDaoConfig.getIdentityScope().clear();
        machineDaoConfig.getIdentityScope().clear();
        manchineTypeDaoConfig.getIdentityScope().clear();
    }

    public RoomDao getRoomDao() {
        return roomDao;
    }

    public MachineDao getMachineDao() {
        return machineDao;
    }

    public ManchineTypeDao getManchineTypeDao() {
        return manchineTypeDao;
    }

}
